// <auto-generated />
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AutoPartsDbContext))]
    partial class AutoPartsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Двигун і його компоненти"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Гальмівна система"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Електрообладнання та запалювання"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ходова частина (підвіска, рульове управління)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Трансмісія та привід"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Система охолодження"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Вихлопна система"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Паливна система"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Кузовні деталі"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Оптика та освітлення"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Колеса та шини"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Автоелектроніка та мультимедіа"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Інтер’єр та аксесуари"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Рідини та витратні матеріали"
                        });
                });

            modelBuilder.Entity("Data.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Німеччина",
                            Name = "Bosch"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Німеччина",
                            Name = "Continental"
                        },
                        new
                        {
                            Id = 3,
                            Country = "США",
                            Name = "Delphi"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Японія",
                            Name = "Denso"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Франція",
                            Name = "Valeo"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Японія",
                            Name = "NGK"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Німеччина",
                            Name = "Sachs"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Німеччина",
                            Name = "Bilstein"
                        });
                });

            modelBuilder.Entity("Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "info@autotrade.ua",
                            Name = "AutoTrade"
                        },
                        new
                        {
                            Id = 2,
                            Contact = "sales@partsexpress.pl",
                            Name = "PartsExpress"
                        },
                        new
                        {
                            Id = 3,
                            Contact = "support@europarts.de",
                            Name = "EuroParts"
                        },
                        new
                        {
                            Id = 4,
                            Contact = "contact@globalauto.com",
                            Name = "GlobalAuto"
                        });
                });

            modelBuilder.Entity("Data.Entities.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("ProviderId");

                    b.ToTable("SpareParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Високоякісні гальмівні колодки Bosch для надійного гальмування.",
                            ImageUrl = "https://content.rozetka.com.ua/goods/images/big/498080167.jpg",
                            Name = "Дискові гальмівні колодки Bosch",
                            PartNumber = "8570259",
                            Price = 1200.5f,
                            ProducerId = 1,
                            ProviderId = 1,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Свічки запалювання преміум-класу від NGK для покращення ефективності двигуна.",
                            ImageUrl = "https://content1.rozetka.com.ua/goods/images/big/347984637.jpg",
                            Name = "Свічки запалювання NGK VAG",
                            PartNumber = "BKUR6ET-10/2397",
                            Price = 350.75f,
                            ProducerId = 6,
                            ProviderId = 2,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Надійний амортизатор Sachs для комфортної їзди.",
                            ImageUrl = "https://content.rozetka.com.ua/goods/images/big/299470781.jpg",
                            Name = "Амортизатор Sachs (передній) VAG",
                            PartNumber = "315087",
                            Price = 2500.99f,
                            ProducerId = 7,
                            ProviderId = 3,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 8,
                            Description = "Високопродуктивний паливний насос Denso для стабільної подачі пального.",
                            ImageUrl = "https://img.dok.ua/images/card/product/0320/16/904005_1.jpg",
                            Name = "Паливний насос Denso DFP-0106",
                            PartNumber = "01209160",
                            Price = 3200f,
                            ProducerId = 4,
                            ProviderId = 4,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("Data.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Title = "Блок двигуна"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Title = "Головка блока циліндрів"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Title = "Поршні та кільця"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Title = "Клапани та розпредвал"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Title = "Колінчастий вал"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Title = "Турбокомпресор"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Title = "Масляний насос"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Title = "Прокладки та ущільнення"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Title = "Гальмівні диски"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Title = "Гальмівні колодки"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Title = "Гальмівні барабани"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Title = "Гальмівні шланги"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Title = "Головний гальмівний циліндр"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Title = "ABS-сенсори"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Title = "Стартер"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Title = "Генератор"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Title = "Акумулятор"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Title = "Свічки запалювання"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Title = "Котушка запалювання"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Title = "Датчики (кисневий, температури, тиску тощо)"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Title = "Електропроводка"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Title = "Амортизатори"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Title = "Пружини підвіски"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Title = "Кульові опори"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Title = "Рульові тяги та наконечники"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Title = "Стабілізатори та втулки"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Title = "Рульова рейка"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Title = "Підшипники маточини"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Title = "Зчеплення"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Title = "КПП"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Title = "Привідні вали та ШРУСи"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Title = "Роздавальна коробка"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Title = "Мости та диференціал"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Title = "Радіатор охолодження"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            Title = "Водяний насос (помпа)"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            Title = "Термостат"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 6,
                            Title = "Вентилятор"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            Title = "Розширювальний бачок"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Title = "Шланги та патрубки"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            Title = "Глушник"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            Title = "Каталізатор"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 7,
                            Title = "Лямбда-зонд"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            Title = "Резонатор"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            Title = "Випускний колектор"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            Title = "Паливний насос"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 8,
                            Title = "Форсунки"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            Title = "Карбюратор"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            Title = "Бензобак"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 8,
                            Title = "Паливний фільтр"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 8,
                            Title = "Рампа"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 9,
                            Title = "Капот"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 9,
                            Title = "Двері"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 9,
                            Title = "Крила"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 9,
                            Title = "Бампери"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 9,
                            Title = "Дзеркала"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 9,
                            Title = "Скло (лобове, бічне, заднє)"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 9,
                            Title = "Фари та задні ліхтарі"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 10,
                            Title = "Фари головного світла"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            Title = "Протитуманні фари"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 10,
                            Title = "Ліхтарі заднього ходу"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 10,
                            Title = "Габаритні вогні"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 10,
                            Title = "Лампи та LED-елементи"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 11,
                            Title = "Диски (легкосплавні, сталеві)"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 11,
                            Title = "Шини"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 11,
                            Title = "Гайки та болти кріплення"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 12,
                            Title = "Бортовий комп’ютер"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 12,
                            Title = "Камера заднього виду"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 12,
                            Title = "Парктроніки"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 12,
                            Title = "Магнітола"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 12,
                            Title = "Дисплеї та мультимедійні системи"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 13,
                            Title = "Кермо"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 13,
                            Title = "Сидіння"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 13,
                            Title = "Панель приладів"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 13,
                            Title = "Килимки"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 13,
                            Title = "Підлокітники"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 14,
                            Title = "Масло моторне/трансмісійне"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 14,
                            Title = "Антифриз"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 14,
                            Title = "Гальмівна рідина"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 14,
                            Title = "Омивач скла"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 14,
                            Title = "Мастильні матеріали"
                        });
                });

            modelBuilder.Entity("Data.Entities.SparePart", b =>
                {
                    b.HasOne("Data.Entities.Category", "Category")
                        .WithMany("SpareParts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Producer", "Producer")
                        .WithMany("Parts")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Provider", "Provider")
                        .WithMany("Parts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Producer");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Data.Entities.SubCategory", b =>
                {
                    b.HasOne("Data.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Navigation("SpareParts");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Data.Entities.Producer", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Data.Entities.Provider", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
